sudo: required

services:
  - docker

notifications:
  email:
    on_success: never
    on_failure: always

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - /^redis-locks-.*$/

env:
   - GRADLE_VERSION="2.14-rc-2"

before_install:
   - "export COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
   - wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
   - unzip gradle-$GRADLE_VERSION-bin.zip
   - export GRADLE_HOME=$PWD/gradle-$GRADLE_VERSION
   - export PATH=$GRADLE_HOME/bin:$PATH
   - docker pull redis:alpine

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: /bin/true

script: if [ ! -z "$TRAVIS_TAG" ] || [[ "$COMMIT_MSG" != 'Release redis-locks'* ]] ; then gradle check; fi

after_success: if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ ! -z "$TRAVIS_TAG" ] ; then gradle bintrayUpload; fi
